" Plugins here
" =============
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/vundle'

Plugin 'bling/vim-airline'
Plugin 'scrooloose/nerdtree.git'
Plugin 'scrooloose/syntastic'

call vundle#end()
filetype plugin indent on

" Open Nerd Tree
map <C-n> :NERDTreeToggle<CR>

" Appearance
" ==========
syntax on
syntax enable

let g:airline_powerline_fonts = 1
set noshowmode

" General Config
" ==============
set number                      " Line numbers are nice
set history=100                 " Store lots of :cmdline history
set showcmd                     " Show incomplete cmds down the bottom
set autoread                    " Reload files changed outside vim
set laststatus=2                " Always show status line
set hidden                      " Buffers can exist in the background
set splitright                  " Opens vertical split right of current window
set splitbelow                  " Opens horizontal split below current window

" Search Settings
" ===============

set incsearch        " Find the next match as we type the search
set hlsearch         " Highlight searches by default

" Turn Off Swap Files
" ===================
set noswapfile
set nobackup
set nowritebackup
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp

" Indentation and Display
" =======================
set autoindent
set smartindent
set smarttab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set expandtab

" Start scrolling when we're getting close to margins
set scrolloff=13
set sidescrolloff=15
set sidescroll=1
