fpath+=$HOME/.zfunc

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.config/zsh/oh-my-zsh
[ ! -d "$ZSH" ] && \
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended  --keep-zshrc

# ZSH_THEME="af-magic"
# ZSH_THEME="sorin"
ZSH_THEME="simple"

# Do not query the user before executing rm *
setopt RM_STAR_SILENT

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
plugins=(git colorize compleat)

source $ZSH/oh-my-zsh.sh

BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
  [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
    eval "$("$BASE16_SHELL/profile_helper.sh")"

