source $HOME/.zprofile

BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"

# dh-make env variables
DEBEMAIL="bernardo.mferrari@gmail.com"
DEBFULLNAME="Bernardo Ferrari Mendonca"
export DEBEMAIL DEBFULLNAME

fpath+=$HOME/.zfunc

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# ZSH_THEME="af-magic"
# ZSH_THEME="sorin"
ZSH_THEME="simple"

# Do not query the user before executing rm *
setopt RM_STAR_SILENT

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
plugins=(git colorize compleat)

source $ZSH/oh-my-zsh.sh

git config --global user.name "tarberd"
git config --global user.email bernardo.mferrari@gmail.com 
git config --global core.editor nvim
MOZ_ENABLE_WAYLAND=1
