# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# ZSH_THEME="af-magic"
# ZSH_THEME="sorin"
ZSH_THEME="simple"

# Do not query the user before executing rm *
setopt RM_STAR_SILENT

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
plugins=(git colorize compleat)

source $ZSH/oh-my-zsh.sh

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"

# You may need to manually set your language environment
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# dh-make env variables
DEBEMAIL="bernardo.mferrari@gmail.com"
DEBFULLNAME="Bernardo Ferrari Mendonca"
export DEBEMAIL DEBFULLNAME
