# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="af-magic"

# Do not query the user before executing rm * 
setopt RM_STAR_SILENT

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
plugins=(git command-not-found colorize compleat colored-man-pages)

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"
export PATH

# dh-make env variables
DEBEMAIL="bernardo.mferrari@gmail.com"
DEBFULLNAME="Bernardo Ferrari Mendonca"
export DEBEMAIL DEBFULLNAME
